// Generated by CoffeeScript 1.7.1
var quick_create_index;

quick_create_index = 0;

$(function() {
  $('#quick-create').on('keyup', 'input[type=text]', function(e) {
    var dropdown, text;
    if (e.which === 91) {
      return true;
    }
    text = $(this).val();
    dropdown = $('#quick-create .options');
    if (text.length > 0) {
      dropdown.removeClass('hidden');
      $('#quick-create .user-value').text(text);
    }
    if (e.which === 27) {
      return dropdown.addClass('hidden');
    }
  });
  $('#quick-create').on('submit', function(e) {
    return e.preventDefault();
  });
  $('body').on('click', function(e) {
    $('#quick-create .options').addClass('hidden');
    if (!$(e.target).is('.actions')) {
      return $('#menu').addClass('hidden');
    }
  });
  $('#overlay').on('click', function(e) {
    return $('#overlay').addClass('hidden');
  });
  $('.actions').on('click', function(e) {
    var menu;
    menu = $('#menu');
    e.preventDefault();
    menu.removeClass('hidden');
    return menu.css({
      top: e.pageY - 5,
      left: e.pageX + 15
    });
  });
  $('.task h4').on('click', function(e) {
    var new_task, original_task;
    e.preventDefault();
    original_task = $(this).parent();
    new_task = original_task.clone();
    $('#overlay .selected-elem').html(new_task);
    $('#overlay .selected-elem').css(original_task.offset());
    console.log(original_task);
    $('#overlay').removeClass('hidden');
    return $('.modal').css({
      top: original_task.offset().top + (original_task[0].offsetHeight / 2) - 75,
      left: original_task.offset().left + original_task[0].offsetWidth + 15
    });
  });
  $('.task').on('dragstart dragend', function(e) {
    return $('.task-actions').toggleClass('invisible');
  });
  $('.task-actions div').on('dragenter', function(e) {
    console.log('drug over action ' + $(this).text());
    return $(this).siblings().addClass('fade-out');
  });
  return $('.task-actions div').on('dragleave', function(e) {
    return $(this).siblings().removeClass('fade-out');
  });
});
