// Generated by CoffeeScript 1.7.1
var CreateTask, QuickCreate, app;

app = angular.module('app', ['ngRoute']);

QuickCreate = function($scope) {
  $scope.create = function() {
    return console.log("create new task");
  };
  return $scope.adv_create = function() {
    console.log("adv create new task");
    return this.$parent.adv_create = true;
  };
};

CreateTask = function($scope) {
  return $scope.add_task = function() {
    if (this.$parent.tasks == null) {
      this.$parent.tasks = [];
    }
    if ($scope.difficulty == null) {
      $scope.difficulty = 0;
    }
    this.$parent.tasks.push({
      title: $scope.title,
      due_date: $scope.due_date,
      description: $scope.description,
      points: 5 + (2 * +$scope.difficulty),
      chain: 1
    });
    return this.$parent.adv_create = false;
  };
};
