// Generated by CoffeeScript 1.7.1
var QuickCreate;

QuickCreate = function($scope) {
  $scope.create = function() {
    return console.log("create new task");
  };
  return $scope.adv_create = function() {
    return console.log("adv create new task");
  };
};
