// Generated by CoffeeScript 1.7.1
define(['jquery', 'underscore', 'backbone', 'models/Tasks', 'models/Task'], function($, _, Backbone) {
  var Task, Tasks;
  Tasks = require('models/Tasks');
  Task = require('models/Task');
  return Backbone.View.extend({
    el: "#create-overlay",
    events: {
      "submit #create-task": "submit"
    },
    initialize: function() {
      this.modal = this.$('#create');
      this.form = this.$('#create-task');
      return window.tasks != null ? window.tasks : window.tasks = new Tasks;
    },
    submit: function(e) {
      var form_data;
      e.preventDefault();
      form_data = this.form.serializeArray();
      return window.tasks.add(new Task({
        "title": form_data[0].value
      }));
    }
  });
});
