// Generated by CoffeeScript 1.7.1
define(['jquery', 'underscore', 'backbone', 'views/Task'], function($, _, Backbone) {
  var Task;
  Task = require('views/Task');
  console.log(Task);
  return Backbone.View.extend({
    el: '#tasks',
    initialize: function(options) {
      this.tasks = options.tasks;
      return this.listenTo(this.tasks, 'add', this.add_task);
    },
    add_task: function(task) {
      console.log("task added", task);
      return this.$el.append((new Task({
        task: task
      })).$el);
    }
  });
});
