// Generated by CoffeeScript 1.7.1
define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
  return Backbone.View.extend({
    initialize: function(options) {
      this.tasks = options.tasks;
      return this.listenTo(this.tasks, 'add', function() {
        return console.log("task added");
      });
    }
  });
});
