// Generated by CoffeeScript 1.7.1
define(['jquery', 'underscore', 'backbone', 'models/Task'], function($, _, Backbone) {
  return Backbone.View.extend({
    el: '#task-tpl',
    initialize: function(options) {
      this.model = options.task;
      return console.log("new task view with task", this.model);
    }
  });
});
