// Generated by CoffeeScript 1.7.1
define(['jquery', 'underscore', 'backbone', 'js/Task'], function($, _, Backbone) {
  var Task;
  Task = require('js/Task');
  return Backbone.Collection.extend({
    model: Task,
    localStorage: new Backbone.LocalStorage("achievable")
  });
});
