// Generated by CoffeeScript 1.7.1
define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
  return Backbone.Model.extend({
    defaults: function() {
      return {
        created: new Date()
      };
    }
  });
});
