// Generated by CoffeeScript 1.7.1
define(['jquery', 'underscore', 'backbone', 'models/Task'], function($, _, Backbone) {
  var Task;
  Task = require('models/Task');
  return Backbone.Collection.extend({
    model: Task
  });
});
