// Generated by CoffeeScript 1.7.1
var QuickCreate;

QuickCreate = function($scope) {
  $scope.create = function() {
    if (this.$parent.tasks == null) {
      this.$parent.tasks = [];
    }
    this.$parent.tasks.push({
      title: this.title,
      created: new Date(),
      modified: new Date(),
      description: "",
      points: {
        total: 5,
        base: 5,
        motivation: 0,
        chain: 0
      },
      chain: 0,
      motivation: 0
    });
    return this.title = "";
  };
  return $scope.adv_create = function() {
    console.log("adv create new task");
    this.$parent.adv_create = true;
    this.$parent.title = this.title;
    return this.title = "";
  };
};
