// Generated by CoffeeScript 1.7.1
var TasksController;

TasksController = function($scope) {
  $scope.sections = [
    {
      icon: 'D',
      name: 'details'
    }, {
      icon: 'P',
      name: 'points'
    }
  ];
  $scope.short_description = function() {
    if (this.task.description.length < 75) {
      return this.task.description;
    } else {
      return this.task.description.substr(0, 75) + "...";
    }
  };
  $scope.days_msg = function() {
    var days_msg, days_remaining;
    days_remaining = this.days_remaining();
    if (days_remaining < 0) {
      days_msg = "LATE";
    }
    if (days_remaining === 0) {
      days_msg = "Today";
    }
    if (days_remaining === 1) {
      days_msg = "1 Day";
    }
    if (days_remaining > 1) {
      days_msg = "" + days_remaining + " Days";
    }
    if (days_remaining >= 100) {
      days_msg = "Far";
    }
    return days_msg;
  };
  $scope.days_remaining = function() {
    var remaining;
    remaining = Math.round((this.task.due_date - new Date()) / (1000 * 60 * 60 * 24));
    if (remaining >= 10) {
      remaining = "future";
    }
    if (remaining < 0) {
      remaining = -1;
    }
    return remaining;
  };
  $scope.due_date = function() {
    if (this.task.due_date != null) {
      return this.date(this.task.due_date);
    }
  };
  $scope.created = function() {
    return this.date(this.task.created);
  };
  $scope.modified = function() {
    return this.date(this.task.modified);
  };
  $scope.date = function(date) {
    return [date.getFullYear(), this.pad(date.getMonth() + 1), this.pad(date.getDate())].join('/');
  };
  return $scope.pad = function(val) {
    if (val < 10) {
      return "0" + val;
    } else {
      return val;
    }
  };
};
